### ISSUE TITLE
Not working on Fedora

### ISSUE THREAD

**Issue by daniruiz** [bil-elmoussaoui/nautilus-folder-icons#15]
For installing it in fedora it is also necessary to install pygobject3 and python3-gobject.

Anyway, after installing it the icon selector menu works well but when I select the icon the folder doesn't change.

**Comment by bilelmoussaoui** [comment]
You can create a PR to add the fedora dependencies to the list. Even If think those should be added directly to python-nautilus instead ;)

Can you try to kill Nautilus `nautilus -q`, reopen it again using the terminal and apply a different icon to a folder and paste the output here, please?

Thanks!

**Comment by daniruiz** [comment]
Thanks for your reply. I don't know why it did not work before but now it works like a charm.
Nice project ;)
