### ISSUE TITLE
Allow python3 as a dependency

### ISSUE THREAD

**Issue by skewty** [bil-elmoussaoui/nautilus-folder-icons#16]
[nautilus-python 1.2](https://github.com/GNOME/nautilus-python/releases) now works with Python3.

Distros like Ubuntu do not even carry python2 by default anymore.

**Comment by bilelmoussaoui** [comment]
Will fix that this evening!

**Comment by bilelmoussaoui** [comment]
It was already supported. Just updated the documentation with the correct packages names.
