### ISSUE TITLE
Let the category icon be independent of the folder icon

### ISSUE THREAD

**Issue by samgundel** [bil-elmoussaoui/nautilus-folder-icons#26]
It would be nice if the category subicon (e.g. the gear, or gitlab symbol) could be applied to any folder icon. In this way, whatever chosen "theme" (red, blue, orange) could maintain its subicons (settings, gitlab, etc.).

**Comment by bilelmoussaoui** [comment]
That's sadly not possible. The icons can be a bitmap (png) and there's no easy way to merge the simple folder icon with the symbol of the other one.

**Comment by samgundel** [comment]
I will think about it a bit more, one way would be to use [font-awesome](https://github.com/FortAwesome/Font-Awesome)'s icons on top of any user folder icon. It might be that we manually would need to compose a new icon theme for it (perhaps using [imagemagick](https://github.com/ImageMagick/ImageMagick)?). If only I could find the time to code this :)

**Comment by bilelmoussaoui** [comment]
@jambuu It's just tooooo hard to do that I don't plan to spend my time on that. You have to take care of each icon extension (.xpm, .png, .svg, .jpg...). Too complex for a Nautilus extension. 
Already thought about this before, just to automate few things with Numix icon theme and it wasn't even possible as you can't get the perfect position to put the icon on it, the right colors to use and other small issues that make this "an impossible task".
Closing as I don't plan to work on this.
