### ISSUE TITLE
Wrong Python 3 package on README (Arch Linux)

### ISSUE THREAD

**Issue by aldomann** [bil-elmoussaoui/nautilus-folder-icons#29]
As far as I'm concerned, the package for `python3-nautilus` on Arch Linux systems is actually called `python-nautilus` (package info [here](https://www.archlinux.org/packages/community/x86_64/python-nautilus/)). Usually in Arch, only `python2` packages have the version written onto them.

**Comment by bilelmoussaoui** [comment]
Thanks for reporting that! Fixed it.
