### ISSUE TITLE
FAILED: data/nautilus-folder-icons.metainfo.xml 

### ISSUE THREAD

**Issue by jpmolinamatute** [bil-elmoussaoui/nautilus-folder-icons#3]
Hello!

After runing `sudo ninja -C builddir install` I got

ninja: Entering directory `builddir'
[1/2] Generating nautilus-folder-icons.metainfo.xml_merge with a custom command.
FAILED: data/nautilus-folder-icons.metainfo.xml 
/usr/bin/meson --internal msgfmthelper ../data/nautilus-folder-icons.metainfo.xml.in data/nautilus-folder-icons.metainfo.xml xml ../data/../po
msgfmt: cannot locate ITS rules for ../data/nautilus-folder-icons.metainfo.xml.in
ninja: build stopped: subcommand failed.
do you know how to fix it?

another thing you should state this app depend on python 3 (for those who uses python 2)

awesome project BTW! :-)

**Comment by bilelmoussaoui** [comment]
the app doesn't depend on python 3 but python 2!

**Comment by bilelmoussaoui** [comment]
And you need to install appstream-glib
you might need to install the -dev version if you're on Ubuntu or -devel version on Fedora

**Comment by jpmolinamatute** [comment]
if I use python2 I get this error:
$  meson builddir --prefix=/usr
Traceback (most recent call last):
  File "/usr/bin/meson", line 17, in <module>
    from mesonbuild import mlog, mesonmain, mesonlib
ImportError: No module named mesonbuild

when using python3  meson build works as expected

**Comment by jpmolinamatute** [comment]
it works! I installed appstream-glib and python2-nautilus and everything works as expected :-)

**Comment by bilelmoussaoui** [comment]
meson is a build system and not a running dependency

**Comment by bilelmoussaoui** [comment]
I will add appstream-glib to the README
