### ISSUE TITLE
Function does not take positional arguments

### ISSUE THREAD

**Issue by AlexAshs** [bil-elmoussaoui/nautilus-folder-icons#37]
Currently meson has issues with building GNOME projects, as documented here: https://github.com/mesonbuild/meson/issues/9441

Because of that issue, meson won't build the project, regardless of whether trying to install from the AUR or manually from git.

To be precise the error message is as follows:

data/meson.build:2:5: ERROR: Function does not take positional arguments.

**Comment by cristian-home** [comment]
For me it worked to delete line 4 in the data/meson.build file. I deleted the line 'appdata'.
