### ISSUE TITLE
Cannot manually apply images

### ISSUE THREAD

**Issue by ghost** [bil-elmoussaoui/nautilus-folder-icons#5]
I can see the menu, but I can't click 'Apply' after selecting an image.

**Comment by bilelmoussaoui** [comment]
The image must be a png or an svg. is that the case?

**Comment by ghost** [comment]
Yes, I've tried with both .png and .svg. What I have to do is to just retype 'folder' and a list appears. I cannot manually search for an image and add it that way.

**Comment by bilelmoussaoui** [comment]
The search only works with folder icons which mean icons on your current icon theme that starts with "folder".  Otherwise, you can type whatever icon name you want and the preview will show it if the icon does exist.

**Comment by bilelmoussaoui** [comment]
Ping?

**Comment by bilelmoussaoui** [comment]
I've just fixed an issue that might be related to this
